### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by tomaszduda23** [vegardit/docker-gitea-act-runner#14]
I would like to use runner in version 0.1.6 since there is a but in newer version https://gitea.com/gitea/act_runner/issues/195. It would be nice if you could tag those images with corresponding version on gitea runner.

**Comment by sebthom** [comment]
Fixed by https://github.com/vegardit/docker-gitea-act-runner/commit/fccc482c5d9e4cd6196d675cf1c7e546b5337864
