### ISSUE TITLE
failure in /opt/run_runner.sh during startup.

### ISSUE THREAD

**Issue by wblew** [vegardit/docker-gitea-act-runner#19]
Commit 5dd910707adb2bd095ad71c3b62116c8ffc8c579 broke startup. It introduced backtick chars into a comment in the image/config.template.yaml file. During that file's expansion by /opt/run_runner.sh those backticks cause script failure.

Here is some tracing with the `GITEA_RUNNER_LOG_EFFECTIVE_CONFIG: true`
```
gitea-runner-runner-1  |   # Like: ["macos-arm64:host", "ubuntu-latest:docker://node:16-bullseye", "ubuntu-22.04:docker://node:16-bullseye"]
gitea-runner-runner-1  |   # If it's empty when registering, it will ask for inputting labels.
gitea-runner-runner-1  | /opt/run_runner.sh: line 45: deamon: command not found
gitea-runner-runner-1  | /opt/run_runner.sh: line 45: .runner: command not found
gitea-runner-runner-1  |   # If it's empty when execute , will use labels in  file.

```
See my PR #18

**Comment by sebthom** [comment]
With https://github.com/vegardit/docker-gitea-act-runner/commit/6b859904150e3f53a4dd4ebf16bc4c10bd1b291c backticks are no longer expanded/interpolated if present in the YAML file.
