### ISSUE TITLE
Boot loop of latest version

### ISSUE THREAD

**Issue by lanbugs** [vegardit/docker-gitea-act-runner#32]
Hi,

i pulled the last version of act-runner container and tried both versions, he has problems with parsing the configuration.

Following error occurs:

`
act_2-gitea_act_runner-1  | level=info msg="Registering runner, arch=amd64, os=linux, version=v0.2.6."
act_2-gitea_act_runner-1  | level=warning msg="Runner in user-mode."
act_2-gitea_act_runner-1  | Error: parse config file "/tmp/gitea_act_runner_config.yml": yaml: unmarshal errors:
act_2-gitea_act_runner-1  |   line 96: cannot unmarshal !!str `false` into bool
act_2-gitea_act_runner-1  | level=info msg="Registering runner, arch=amd64, os=linux, version=v0.2.6."
act_2-gitea_act_runner-1  | level=warning msg="Runner in user-mode."
act_2-gitea_act_runner-1  | Error: parse config file "/tmp/gitea_act_runner_config.yml": yaml: unmarshal errors:
act_2-gitea_act_runner-1  |   line 96: cannot unmarshal !!str `false` into bool
act_2-gitea_act_runner-1  | level=info msg="Registering runner, arch=amd64, os=linux, version=v0.2.6."
act_2-gitea_act_runner-1  | level=warning msg="Runner in user-mode."
act_2-gitea_act_runner-1  | Error: parse config file "/tmp/gitea_act_runner_config.yml": yaml: unmarshal errors:
act_2-gitea_act_runner-1  |   line 96: cannot unmarshal !!str `false` into bool
act_2-gitea_act_runner-1  | level=info msg="Registering runner, arch=amd64, os=linux, version=v0.2.6."
act_2-gitea_act_runner-1  | level=warning msg="Runner in user-mode."
act_2-gitea_act_runner-1  | Error: parse config file "/tmp/gitea_act_runner_config.yml": yaml: unmarshal errors:
act_2-gitea_act_runner-1  |   line 96: cannot unmarshal !!str `false` into bool
act_2-gitea_act_runner-1  | level=info msg="Registering runner, arch=amd64, os=linux, version=v0.2.6."
act_2-gitea_act_runner-1  | level=warning msg="Runner in user-mode."
act_2-gitea_act_runner-1  | Error: parse config file "/tmp/gitea_act_runner_config.yml": yaml: unmarshal errors:
act_2-gitea_act_runner-1  |   line 96: cannot unmarshal !!str `false` into bool
`

Regards,

Max

**Comment by lanbugs** [comment]
Additional info: dind-0.2.5 is working, latest and 0.2.6 is broken.

**Comment by lltr** [comment]
Having the same issue, reverting to dind-0.2.5
