### ISSUE TITLE
What are the differences compated to gitea/act_runner?

### ISSUE THREAD

**Issue by bserem** [vegardit/docker-gitea-act-runner#35]
Forgive my ignorance here, but I understand that https://gitea.com/gitea/act_runner can also run in docker using the gitea/act_runner image:

```
docker run -e GITEA_INSTANCE_URL=https://your_gitea.com -e GITEA_RUNNER_REGISTRATION_TOKEN=<your_token> -v /var/run/docker.sock:/var/run/docker.sock --name my_runner gitea/act_runner:nightly
```

How is this repo different? Why should one prefer this over the official one?

I admit that using this repo solves a big problem of mine. The `GITEA_RUNNER_JOB_CONTAINER_NETWORK` allows workers to communicate with Gitea, whereas if I use the official act_runner I can't achieve that.
However, I am still intrigued to understand the differences between this and the official one.

Thanks

**Comment by sebthom** [comment]
I created this docker image before the other was available. I guess the main difference is that it is based on Debian instead of Alpine and that you can configure most settings via environment variables.

**Comment by bserem** [comment]
Thanks for the response! That covers everything I guess.

Again, great stuff. Thank you!
