### ISSUE TITLE
bash-init.sh

### ISSUE THREAD

**Issue by zoxendine** [vegardit/docker-gitea-act-runner#38]
Trying to use this repository with a different debian image due to restrictions for my product. But I don't know see the bash-init.sh anywhere in the repo for reference?
 COPY .shared/lib/bash-init.sh /opt/bash-init.sh

**Comment by sebthom** [comment]
It is located here https://github.com/vegardit/docker-shared/blob/v1/lib/bash-init.sh

We use the same bash init script in multiple dockerbrepos/images so it is in a shared repo.
