### ISSUE TITLE
Improve README: Add requirements section 

### ISSUE THREAD

**Issue by rmundel** [vegardit/docker-gitea-act-runner#40]
Hey, first of all, great work!

Second, is that I don't know if it's a requirement for all three runner flavors, but to made it work with the docker-out-of-docker it is necessary to create the _act_ user on the docker host.

- Create the act user:
`adduser --system --no-create-home act`

- Add created user in the docker group
`usermod -aG docker act`

- Set the correct permissions in the data folder
`chown -R act:docker /your-path/data/`

Maybe add that to some **Requirements** section for the readme instructions?

I can make some PR if thats correct.

Thanks.

**Comment by rmundel** [comment]
To add some more context:

I'm migrating for a manual act_runner to your pre-built docker image and getting some wierd permissions errors that were not happening before.

Maybe I'm getting something wrong here.

Please let me know.

**Comment by rmundel** [comment]
Nevermind, I was messing thing up.

**Comment by sebthom** [comment]
Do you think the documentation should be clarified somewhere?

**Comment by rmundel** [comment]
Don't know yet for sure. I'm working my way out.

Currently I'm struggling with some permission trying to use docker/setup-buildx-action@v3

The runner user inside (UID 1001) can't acces docker.sock, but when I try using sudo (it runs with the runneradmin user UID 1000).
