### ISSUE TITLE
missing information on how to start the embedded cache server

### ISSUE THREAD

**Issue by dsl400** [vegardit/docker-gitea-act-runner#59]
there are a few hints about act runner having an embedded cache server but there is no information on how to start it
am I missing something ?

**Comment by sebthom** [comment]
as documented in the readme it is controlled by the environment variable ACT_CACHE_SERVER_ENABLED and it is enabled by default.

what else is unclear?

**Comment by dsl400** [comment]
ACT_CACHE_SERVER_ENABLED disables or enables the cache functionality but there is no command that starts the cache server embedded in act-runner

**Comment by sebthom** [comment]
based on the documentation in the official act_runner repo it should start the server. if it does not please raise an issue in https://gitea.com/gitea/act_runner/issues

**Comment by dsl400** [comment]
it indeed starts and it is accessible in dind configuration
using hosts docker i could not get it to work.
