### ISSUE TITLE
consider adding jq 

### ISSUE THREAD

**Issue by dsl400** [vegardit/docker-gitea-act-runner#60]
Everything is about json there days. Can we add jq to the list of preinstalled tools ?

**Comment by sebthom** [comment]
What is your use-case? The actual gitea actions in a workflow run are not executed inside contains of this image but in containers of images specified by the GITEA_RUNNER_LABELS, e.g. catthehacker/ubuntu:act-22.04

**Comment by dsl400** [comment]
@sebthom yep, you are 100% right :D
