### ISSUE TITLE
[Question] How to run actions on windows / use windows image

### ISSUE THREAD

**Issue by WorldTeacher** [vegardit/docker-gitea-act-runner#62]
Hi, 

i recently switched over to your gitea-act-runner and really like it. I have some builds that need to happen on windows and am not sure on how to do that. Is that possible with this runner?
I am relatively new to using actions, so i might just have overlooked some stuff.

Any help is appreciated.

edit: 
I tried adding a runner label
windows-latest:docker://mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2022
but that did not work

**Comment by sebthom** [comment]
Hmm, good question, I have no experience with Windows builds, but I doubt that it works with a Linux based docker deamon.

**Comment by WorldTeacher** [comment]
I also tried getting the runner working on a windows VM but there the process fails, probably because the runner is set to host and asks for UAC every time an action is called

**Comment by WorldTeacher** [comment]
The mcr.(...) is apparently an image for github actions, but no clue on how to apply it
