### ISSUE TITLE
folder permission error

### ISSUE THREAD

**Issue by linger123** [vegardit/docker-gitea-act-runner#63]
when i run gitea_act_runner , i have this error. 

gitea_act_runner  | /opt/run_runner.sh: line 12: cd: /data: Permission denied
gitea_act_runner  | 19:12:26 Error - exited with status 1 in [/opt/run_runner.sh] at line 12:
gitea_act_runner  |      9	
gitea_act_runner  |     10	log INFO "Effective user: $(id)"
gitea_act_runner  |     11	
gitea_act_runner  |     12	cd /data

**Comment by mohmadhabib** [comment]
I have The Same Issue, How could you solve it ?
