### ISSUE TITLE
[Question] How to declare custom label

### ISSUE THREAD

**Issue by WorldTeacher** [vegardit/docker-gitea-act-runner#67]
I am once again testing how to automate windows builds using actions. 
I have added this to the ENV:
```GITEA_RUNNER_LABELS = ubuntu-latest:docker://catthehacker/ubuntu:act-22.04,ubuntu-22.04:docker://catthehacker/ubuntu:act-22.04,ubuntu-20.04:docker://catthehacker/ubuntu:act-20.04,windows-2022:docker://mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2022```

but no matter what I try, I only get  these labels: `ubuntu-latest`  `ubuntu-22.04`  `ubuntu-20.04` 

How can I add a custom label that uses the provided image (assuming I can pull it in the Docker-in-Docker approach, unRaid is unable to download the image and gives this error:
```
docker pull mcr.microsoft.com/windows/servercore:ltsc2022-amd64   
ltsc2022-amd64: Pulling from windows/servercore
2c91985a0408: Pulling fs layer 
13a330a51786: Pulling fs layer 
image operating system "windows" cannot be used on this platform: operating system is not supported
```

Any help is appreciated

**Comment by sebthom** [comment]
Declaring custom labels only worked during registration in older versions of the act runner. In the meantime they added the option to specify labels directly in the config. I now adjusted the config of the docker image to support this as well. Customizing labels vial GITEA_RUNNER_LABELS should work now as expected.
