### ISSUE TITLE
ghcr.io doesn't provide this image

### ISSUE THREAD

**Issue by alexislefebvre** [vegardit/docker-gitea-act-runner#69]
Here we see an image hosted by `ghcr.io`: https://github.com/vegardit/docker-gitea-act-runner/blob/fe640e7d1df746eba46286110fe96d442bb15108/README.md#L79

But this image is not reachable:

```bash
$ docker pull ghcr.io/vegardit/gitea-act-runner:latest
Error response from daemon: Head "https://ghcr.io/v2/vegardit/gitea-act-runner/manifests/latest": unauthorized
```

This organisation has no repository https://github.com/orgs/vegardit/packages

**Comment by sebthom** [comment]
Actually the packages exist but were set to private visibility for some reason. thanks for reporting!
