### ISSUE TITLE
workflows/build.yml fails to push built images to registry

### ISSUE THREAD

**Issue by wblew** [vegardit/docker-gitea-act-runner#8]
I noticed that the PR #6 changes were not present in images built after its merge.

To reproduce, run:
   `docker run --rm vegardit/gitea-act-runner:latest cat /opt/run.sh`
Observe that that run.sh contains:
   ` sudo usermod -o -u "$GITEA_RUNNER_GID" act`
Rather than:
   ` sudo usermod -o -g "$GITEA_RUNNER_GID" act`

After an investigation, I think the situation can be traced to these lines (with `DOCKER_PUSH=0`):
https://github.com/vegardit/docker-gitea-act-runner/blob/aa822e12ee411469c4421123b62efbb712bc337c/build-image.sh#L47-L50

Adding mult-arch building, changed the BuildKit builder from the docker driver, to the docker-container driver.

However, the docker-container driver does not load its built images into the job container's docker engine registry.

Result? The docker pull at L50, pulls stale arch specific images built _before_ the multi-arch merge commit 313f3780238fe2c51661f8daaa26594318d88a6e.

**Comment by sebthom** [comment]
Thanks for reporting. I changed the build script. Please check again.

**Comment by wblew** [comment]
Checked, and confirmed it's fixed.
